/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:4f5f4189-6eef-4978-afdc-76d0cc6fae8d",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_BGysMYGNU",
    "aws_user_pools_web_client_id": "3dr1erjfdmcnc062o85nkk17sm",
    "oauth": {}
};


export default awsmobile;
